version: '3.7'


services: 
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - ./core:/code
        ports: 
            - 8001:8000
        env_file: 
            - ./django.env
        depends_on: 
            - db

    db:
        image: postgres:12.0-alpine
        environment: 
            - POSTGRES_USER=hello
            - POSTGRES_PASSWORD=hello
            - POSTGRES_DB=hello_db
        volumes: 
            - postgresql_data:/var/lib/postgres/data/

volumes: 
    postgresql_data:
